import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import "./sample-plan.css";

export const metadata: Metadata = {
  title: "Sample Pain Management Plan | PainConsult AI — PainClinics.com",
  description:
    "See a real example of a PainConsult AI personalized pain management plan — covering likely causes, a week-by-week recovery protocol, specialist questions, and red flags for neck and upper back pain.",
  robots: { index: true, follow: true },
  alternates: {
    canonical: "/consult/sample-plan",
  },
  openGraph: {
    title: "Sample Pain Management Plan | PainConsult AI",
    description:
      "A preview of the $19.99 personalized pain management plan — evidence-based, condition-specific, and delivered instantly to your email.",
    url: "/consult/sample-plan",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Sample Pain Management Plan | PainConsult AI",
    description:
      "See what a personalized AI pain plan looks like before you buy. Covers likely causes, recovery protocol, red flags, and specialist questions.",
  },
};

// Inline SVG lock icon — no external dependency
function LockIcon() {
  return (
    <svg
      className="sp-locked-icon"
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  );
}

function WarnIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      style={{ color: "#c0392b", flexShrink: 0 }}
    >
      <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
      <line x1="12" y1="9" x2="12" y2="13" />
      <line x1="12" y1="17" x2="12.01" y2="17" />
    </svg>
  );
}

export default function SamplePlanPage() {
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "MedicalWebPage",
    name: "Sample Pain Management Plan — Neck & Upper Back Pain",
    description:
      "A sample personalized pain management plan generated by PainConsult AI, covering likely causes, immediate action steps, a week-by-week recovery protocol, specialist questions, and red flag symptoms for neck and upper back pain.",
    url: "https://painclinics.com/consult/sample-plan",
    isPartOf: {
      "@type": "WebSite",
      name: "PainClinics.com",
      url: "https://painclinics.com",
    },
    about: {
      "@type": "MedicalCondition",
      name: "Neck and Upper Back Pain",
    },
    author: {
      "@type": "Organization",
      name: "PainClinics.com",
      url: "https://painclinics.com",
    },
  };

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />

      <div className="sp-page">
        <article className="sp-doc" aria-label="Sample Pain Management Plan">

          {/* ── Print-only header (shown on every page via print styles) ── */}
          <header className="sp-print-header" aria-hidden="true">
            <Image
              src="/logo.png"
              alt="PainClinics.com"
              width={100}
              height={32}
              style={{ objectFit: "contain" }}
              priority
            />
            <div className="sp-print-header-text">
              <span className="sp-print-header-site">PainClinics.com</span>
              <span className="sp-print-header-subtitle">Personalized Pain Management Plan</span>
            </div>
          </header>

          {/* ── Screen header ───────────────────────────────────────────── */}
          <header className="sp-doc-header">
            <div className="sp-doc-header-logo">
              <Image
                src="/logo.png"
                alt="PainClinics.com"
                width={120}
                height={38}
                style={{ objectFit: "contain" }}
                priority
              />
            </div>
            <div className="sp-doc-header-text">
              <span className="sp-doc-header-site">PainClinics.com</span>
              <span className="sp-doc-header-subtitle">Personalized Pain Management Plan</span>
            </div>
            <div className="sp-doc-header-rule" aria-hidden="true" />
          </header>

          {/* ── Title Block ─────────────────────────────────────────────── */}
          <div className="sp-title-block">
            <div className="sp-sample-badge" role="note" aria-label="This is a sample preview">
              <span className="sp-sample-badge-dot" aria-hidden="true" />
              SAMPLE — Preview Only. Your plan will be personalized to your symptoms, age, and location.
            </div>

            <h1 className="sp-main-title">Sample Pain Management Plan</h1>
            <p className="sp-condition-label">Neck &amp; Upper Back Pain</p>

            <div className="sp-meta-row">
              <span className="sp-meta-item">Prepared by PainConsult AI</span>
              <span className="sp-meta-dot" aria-hidden="true" />
              <span className="sp-meta-item">{today}</span>
              <span className="sp-meta-dot" aria-hidden="true" />
              <span className="sp-meta-item">painclinics.com</span>
            </div>

            <div className="sp-title-divider" aria-hidden="true" />
          </div>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 1 — UNDERSTANDING YOUR CONDITION (fully visible)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section" aria-labelledby="s1-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">1</div>
              <h2 className="sp-section-title" id="s1-heading">Understanding Your Condition</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <h3 className="sp-sub-heading">Most Likely Causes for Your Profile</h3>
            <div className="sp-prose">
              <p>
                Neck and upper back pain in adults most commonly stems from <strong>cervical spondylosis</strong> (age-related wear of spinal discs and joints), <strong>myofascial pain syndrome</strong> (muscle tension and trigger points), or <strong>postural strain</strong> from forward head positioning common with computer use and mobile devices.
              </p>
            </div>

            <h3 className="sp-sub-heading">Typical Progression</h3>
            <div className="sp-prose">
              <p>
                Without treatment, these conditions often become chronic, with pain intensity fluctuating over months to years. With appropriate intervention, <strong>60–70% of patients experience significant improvement within 4–6 weeks.</strong>
              </p>
              <p>
                With conservative treatment including physical therapy, posture correction, and targeted exercises, most patients achieve substantial pain reduction and functional improvement within <strong>8–12 weeks.</strong>
              </p>
            </div>

            <div className="sp-evidence">
              <div className="sp-evidence-label">Evidence</div>
              <p className="sp-evidence-text">
                According to the NIH, neck pain affects approximately 30% of adults annually, with conservative management successful in 85% of cases when implemented early.
              </p>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 2 — IMMEDIATE ACTION PLAN (partially redacted)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section sp-section--break" aria-labelledby="s2-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">2</div>
              <h2 className="sp-section-title" id="s2-heading">Immediate Action Plan</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <h3 className="sp-sub-heading">Next 72 Hours</h3>

            <div className="sp-field-row">
              <div className="sp-field-label">OTC Medication Protocol</div>
              <div className="sp-locked">
                <LockIcon />
                <div className="sp-locked-inner">
                  <p className="sp-locked-teaser">
                    Specific medication names, dosages, and timing schedules — personalized to your health profile, current medications, and symptom severity.
                  </p>
                  <div className="sp-locked-hint">Included in your personalized plan</div>
                </div>
              </div>
            </div>

            <div className="sp-field-row">
              <div className="sp-field-label">Ice / Heat Protocol</div>
              <div className="sp-field-content">
                <strong>First 48 hours:</strong> Ice pack 15–20 minutes every 2–3 hours to reduce acute inflammation. After 48 hours: Moist heat 15–20 minutes, 3–4 times daily to relax muscle tension and improve circulation.
              </div>
            </div>

            <div className="sp-field-row">
              <div className="sp-field-label">Activity Modifications</div>
              <ul className="sp-list" style={{ marginBottom: "10px" }}>
                <li>Avoid prolonged static neck positions — set a timer to move every 30 minutes</li>
                <li>Sleep with a supportive cervical pillow in a neutral spine position</li>
              </ul>
              <div className="sp-locked">
                <LockIcon />
                <div className="sp-locked-inner">
                  <p className="sp-locked-teaser">
                    3 additional activity modifications specific to your occupation, daily routine, and pain triggers.
                  </p>
                  <div className="sp-locked-hint">Included in your personalized plan</div>
                </div>
              </div>
            </div>

            <div className="sp-field-row">
              <div className="sp-field-label">Sleep Position Guidance</div>
              <div className="sp-locked sp-locked--inline">
                <LockIcon />
                <div className="sp-locked-inner">
                  <p className="sp-locked-teaser">
                    Optimal sleeping positions and pillow height recommendations based on your reported sleep habits and pain pattern.
                  </p>
                  <div className="sp-locked-hint">Included in your personalized plan</div>
                </div>
              </div>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 3 — WEEK-BY-WEEK RECOVERY (Week 1 visible)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section sp-section--break" aria-labelledby="s3-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">3</div>
              <h2 className="sp-section-title" id="s3-heading">Week-by-Week Recovery Protocol</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            {/* Week 1 — visible */}
            <div className="sp-week-card">
              <div className="sp-week-label">Week 1 — Acute Phase: Reduce Pain &amp; Restore Range of Motion</div>
              <ul className="sp-week-exercises">
                <li>
                  <strong>Chin tucks</strong> — 10 reps, 3×/day. Gently draw chin straight back (not down). Releases suboccipital compression.
                </li>
                <li>
                  <strong>Shoulder blade squeezes</strong> — 15 reps, 2×/day. Pinch shoulder blades together, hold 3 seconds. Counteracts forward-rounded posture.
                </li>
                <li>
                  <strong>Gentle neck rotation</strong> — 8 reps each direction, 2×/day. Slow, pain-free range only. Stop at the first point of pain.
                </li>
                <li>
                  <strong>Posture reset protocol</strong> — Every 30 minutes at your workstation: ears over shoulders, shoulders over hips. Hold 5 seconds.
                </li>
              </ul>
            </div>

            {/* Weeks 2–4 — locked */}
            <div className="sp-week-locked">
              <LockIcon />
              <div style={{ flex: 1 }}>
                <div className="sp-week-locked-label">Weeks 2–4 — Progressive Strengthening</div>
                <p className="sp-week-locked-teaser">
                  Progressive strengthening exercises, return-to-activity guidelines, self-assessment checklists, and criteria for advancing to the next phase — based on your fitness level and symptom trajectory.
                </p>
              </div>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 4 — SPECIALIST QUESTIONS (fully locked)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section" aria-labelledby="s4-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">4</div>
              <h2 className="sp-section-title" id="s4-heading">Questions for Your Specialist</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <div className="sp-teaser-row">
              <div className="sp-teaser-pill">10 Specific Questions to Ask</div>
              <div className="sp-teaser-pill">3 Diagnostic Tests to Request</div>
            </div>

            <div className="sp-locked">
              <LockIcon />
              <div className="sp-locked-inner">
                <p className="sp-locked-teaser">
                  Personalized questions based on your specific condition, symptoms, duration of pain, and relevant treatment history — designed to get you the most out of a 15-minute appointment.
                </p>
                <div className="sp-locked-hint">Included in your personalized plan</div>
              </div>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 5 — RED FLAGS (fully visible)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section sp-section--break" aria-labelledby="s5-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">5</div>
              <h2 className="sp-section-title" id="s5-heading">Red Flags</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <div className="sp-urgent-box" role="alert">
              <div className="sp-urgent-label">
                <WarnIcon />
                Seek IMMEDIATE Emergency Care if you experience any of the following
              </div>
              <ul className="sp-list sp-list--danger">
                <li>Sudden severe headache with neck stiffness and fever</li>
                <li>Loss of bladder or bowel control</li>
                <li>Progressive weakness in arms or legs</li>
                <li>Severe chest pain radiating from the upper back</li>
                <li>Neck pain following significant trauma with numbness or tingling</li>
                <li>Difficulty swallowing or breathing</li>
                <li>New dizziness or vision changes after neck manipulation</li>
              </ul>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 6 — SPECIALIST GUIDE (partially visible)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section" aria-labelledby="s6-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">6</div>
              <h2 className="sp-section-title" id="s6-heading">Specialist Guide</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <div className="sp-prose">
              <p>
                Start with your <strong>primary care physician</strong> or a <strong>physiatrist</strong> (physical medicine and rehabilitation specialist) for initial evaluation. If conservative treatment does not produce improvement within 4–6 weeks, ask for a referral to a <strong>pain management specialist</strong> or <strong>orthopedic spine specialist</strong>.
              </p>
            </div>

            <div className="sp-field-row" style={{ marginTop: "16px" }}>
              <div className="sp-field-label">Insurance &amp; Cost Estimates</div>
              <div className="sp-locked sp-locked--inline">
                <LockIcon />
                <div className="sp-locked-inner">
                  <p className="sp-locked-teaser">
                    Location-specific insurance networks and out-of-pocket cost estimates based on your zip code, including expected copay ranges for initial consultation, follow-up visits, and common diagnostic tests.
                  </p>
                  <div className="sp-locked-hint">Included in your personalized plan</div>
                </div>
              </div>
            </div>
          </section>

          {/* ══════════════════════════════════════════════════════════════
              SECTION 7 — SELF-CARE & LIFESTYLE (partially visible)
          ══════════════════════════════════════════════════════════════ */}
          <section className="sp-section" aria-labelledby="s7-heading">
            <div className="sp-section-header">
              <div className="sp-section-num" aria-hidden="true">7</div>
              <h2 className="sp-section-title" id="s7-heading">Self-Care &amp; Lifestyle</h2>
              <div className="sp-section-rule" aria-hidden="true" />
            </div>

            <div className="sp-week-card">
              <div className="sp-week-label">Featured Exercise — Levator Scapulae Stretch</div>
              <ul className="sp-week-exercises">
                <li>
                  Sit upright in a chair. Turn your head 45° to the left, then tilt your chin down toward your left armpit. Use your left hand to gently add overpressure. Hold 30 seconds, 3 times each side. Targets the muscle most commonly implicated in neck-to-shoulder pain.
                </li>
              </ul>
            </div>

            <div className="sp-locked">
              <LockIcon />
              <div className="sp-locked-inner">
                <p className="sp-locked-teaser">
                  3 additional targeted exercises, an anti-inflammatory diet guide with specific food recommendations, stress management techniques shown to reduce pain perception, and a sleep optimization protocol — all personalized to your reported lifestyle and symptom profile.
                </p>
                <div className="sp-locked-hint">Included in your personalized plan</div>
              </div>
            </div>
          </section>

          {/* ── CTA Card (screen only via CSS) ──────────────────────────── */}
          <div className="sp-cta-wrapper" aria-label="Purchase your personalized plan">
            <div className="sp-cta-card">
              <div className="sp-cta-eyebrow">PainConsult AI</div>
              <h2 className="sp-cta-title">Get Your Personalized Plan</h2>
              <p className="sp-cta-desc">
                Tailored to your specific symptoms, age, location, and health profile. Includes complete medication protocols, a 4-week recovery schedule, 10 specialist questions, insurance cost estimates, and more.
              </p>
              <div className="sp-cta-price">
                $19.99 <span>— One-time purchase</span>
              </div>
              <Link href="/consult" className="sp-cta-btn">
                Start Your Assessment
              </Link>
              <p className="sp-cta-fine">
                Takes about 5 minutes. Plan delivered to your email immediately.
              </p>
            </div>
          </div>

          {/* ── Disclaimer ──────────────────────────────────────────────── */}
          <footer className="sp-disclaimer">
            <em>
              This sample plan is provided for informational and illustrative purposes only and does not constitute medical advice, diagnosis, or treatment. PainConsult AI is an educational tool. Always consult a qualified healthcare professional before making any changes to your pain management approach. In a medical emergency, call 911 or go to your nearest emergency room immediately.
            </em>
          </footer>

        </article>
      </div>
    </>
  );
}
